# Generated by Django 4.2 on 2023-05-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_url', models.URLField()),
                ('short_url', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
