# Generated by Django 4.2 on 2023-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapidLink', '0004_alter_urlmodel_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='short_url',
            field=models.CharField(max_length=20),
        ),
    ]
